# Generated by Django 3.2 on 2021-04-07 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, default='none', on_delete=django.db.models.deletion.PROTECT, to='library_app.category'),
        ),
    ]
