# Generated by Django 3.2 on 2021-04-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, default='photo/default.jpg', upload_to='photo/%Y/%m/%d'),
        ),
    ]
