# Generated by Django 3.2 on 2021-04-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_alter_book_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rent_day',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
